name: Build & Deploy Filterable MyST Gallery

on:
  #push:
  #  branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GALLERY_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Python & Node dependencies
        run: |
          pip install pyyaml nbformat
          npm install -g mystmd

      - name: Generate gallery page with filtering
        run: python scripts/generate_gallery.py

      - name: Build main gallery
        run: myst build --html

      - name: Prepare deploy folder
        run: |
          mkdir -p full_site
          cp -r _build/html/* full_site/


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: full_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment


      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add myst.yml production/
          git commit -m "Update myst.yml and production after issue close [skip ci]" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
